### PR TITLE
switched project overview to be a byte array

### LINKED ISSUE #3080: [BUG]: the project overview is causing 500 errors
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by dgauldie**
# Description

* Include a summary of the changes and the related issue. 
* Include relevant motivation and context.

Resolves #3080

### CODE REVIEW

**Comment by dgauldie** [comment]
once this PR is merged, we will need to manually delete the overview column on staging and production

File: packages/client/hmi-client/src/components/home/tera-project-overview-editor.vue [hunk 1]
```diff
@@ -8,15 +8,15 @@
...
+import { computed, onMounted, onUnmounted, ref, watch } from 'vue';
 import Editor from 'primevue/editor';
 import { update } from '@/services/project';
 import { useProjects } from '@/composables/project';
 
 const AUTO_SAVE_DELAY = 3000;
 
 const { activeProject, refresh } = useProjects();
-const lastSavedContent = computed(() => activeProject.value?.overviewContent ?? '');
+const lastSavedContent = computed(() => atob(activeProject.value?.overviewContent ?? ''));
```
Comment (YohannParis) [inline packages/client/hmi-client/src/components/home/tera-project-overview-editor.vue:19]: We learn everyday: https://developer.mozilla.org/en-US/docs/Web/API/atob

File: packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ProjectController.java
Comment (YohannParis) [inline packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/ProjectController.java:1]: While on that PR, could you make sure this default value is added if `overviewContent` is null on `getProject`? Like that it is not saved until the user decide to do so.

**Review by YohannParis — APPROVED** [review]

**Review by dvince2 — APPROVED** [review]
