### PR TITLE
fix accordian automatically opening on scroll or edit

### LINKED ISSUE #5280: [BUG]: Model Config Accordion tabs re-open constantly
close the **context** or **diagram** accordion tabs
scroll the page, update a field ect. this will cause these tabs to reopen.

- Link to the project: https://app.staging.terarium.ai/projects/f8501b9d-31ab-4551-bdef-c8e8cd3c7491/workflow/d39fa7b6-f679-475d-8c58-1459888273ae?operator=a569d985-b006-4295-bd55-e89e426bdb3b

### PR DESCRIPTION
**Pull request by mloppie**
# Description

* Accordion of Description and Diagram would automatically open on scroll or edit
* Accordions now operate independently 

Resolves #5280

### CODE REVIEW

File: packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue [hunk 1]
```diff
@@ -82,7 +82,7 @@
 				<Button label="Save as" outlined severity="secondary" @click="showSaveModal = true" />
 				<Button :disabled="isSaveDisabled" label="Save" @click="onSaveConfiguration" />
 			</template>
-			<Accordion multiple :active-index="[0, 1, 2]">
```
Comment (Tom-Szendrey) [inline packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue:85]: I see many many examples around the app of us using a single `Accordion` for multiple `AccordionTab`s
Im not sure why we need to break this down into three Accordions?

**Review by blanchco — APPROVED** [review]
tested and works fine 👍

File: packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue (hunk 1 above)
Comment (YohannParis) [reply packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue:85]: because it's been hacked together over the years. and the model needs a better refactoring that what we got.

**Review by YohannParis — APPROVED** [review]
