### PR TITLE
feat: model sidebar state management, tab bug fixes and, refactoring

### LINKED ISSUE #346: [BUG]: Can't interact with any tabs but the last one
**Describe the bug**
Later tabs appear to render overtop of the earlier ones, blocking mouse events.

**To Reproduce**
1. Go to the models space
2. Select multiple models
3. Click on each of the tabs and try to click the "Show more" button or pan around the graph

**Expected behavior**
Should be able to interact with any of the tabs' content.

**Screenshots**

https://user-images.githubusercontent.com/16928557/206500406-2bc68c1e-86c5-4b89-bf93-a8b3c969241e.mov

### PR DESCRIPTION
**Pull request by echl**
# Description

Open, close, and remove tabs from the model side bar. Keep tab state when navigating away from model page. 

Resolves #346 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide reproduction instructions and list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/services/hmi-server/src/main/resources/application.properties [hunk 1]
```diff
@@ -21,7 +21,7 @@ mp.openapi.extensions.smallrye.info.description=REST endpoints for the TERArium
 ########################################################################################################################
 # Microservice configurations
 ########################################################################################################################
-%dev.data-service/mp-rest/url=http://localhost:3020
+%dev.data-service/mp-rest/url=http://localhost:8001
```
Comment (YohannParis) [inline packages/services/hmi-server/src/main/resources/application.properties:24]: Do NOT add this file this *WILL* brake the app.
You can now use the container version in the cluster.

File: packages/client/hmi-client/src/views/ModelView.vue [hunk 2]
```diff
@@ -1,28 +1,37 @@
...
+
+// @ts-ignore
+// eslint-disable-next-line @typescript-eslint/no-unused-vars
+tabStore.$subscribe((mutation, state) => {
+	const savedTabs = state.tabMap.get(tabContext);
+	if (savedTabs) {
+		openTabs.value = savedTabs;
+	}
+	activeTabIndex.value = tabStore.getActiveTabIndex(tabContext);
+});
```
Comment (YohannParis) [inline packages/client/hmi-client/src/views/ModelView.vue:31]: Could you explain what this `$subscribe` method and what does it do.
Also, let's try to not use `@ts-ignore`

File: packages/client/hmi-client/src/components/tabs/TabContainer.vue [hunk 3]
```diff
@@ -22,16 +22,19 @@ const props = defineProps<{
 	activeTabIndex: number;
 }>();
 
-const emit = defineEmits(['closeTab']);
+const emit = defineEmits<{
+	(e: 'tabClosed', index: number): void;
+	(e: 'tabSelected', index: number): void;
```
Comment (YohannParis) [inline packages/client/hmi-client/src/components/tabs/TabContainer.vue:27]: @bencodrington @mwdchang I forgot if we used pascalCase or kebab-case for events?

File: packages/client/hmi-client/src/components/tabs/Tab.vue [hunk 4]
```diff
@@ -96,12 +96,14 @@ section {
 .content {
 	background-color: white;
 	visibility: hidden;
+	z-index: 0;
```
Comment (YohannParis) [inline packages/client/hmi-client/src/components/tabs/Tab.vue:99]: Please add `isolation: isolate;` on the `.outer-container` to make sure those z-index conflicts with nothing else.

File: packages/client/hmi-client/src/views/ModelView.vue (hunk 2 above)
Comment (echl) [reply packages/client/hmi-client/src/views/ModelView.vue:31]: Unfortunately, I have to here because of the `mutation` variable, which I have to include (just declaring `state` does not work)

**Review by YohannParis — APPROVED** [review]
LGTM
