### PR TITLE
fix: links in reference should be clickable; fix searchbar losing focus when autocomplete occurs

### LINKED ISSUE #557: [BUG]: Links in reference should be clickable
**Describe the bug**
When reviewing references in the preview panel, URLs should be clickable so that the user does not need to copy and paste. 

**To Reproduce**
Open the preview panel for a paper, open the references, references with URLs are not clickable

**Expected behavior**
References with URLs should be clickable

**Screenshots**
image

**Additional context**

### LINKED ISSUE #629: [BUG]: Searchbar loses focus after autocomplete.
Searchbar loses focus after autocomplete.

### PR DESCRIPTION
**Pull request by echl**
https://user-images.githubusercontent.com/16358728/215898232-ddcc3bce-9ae1-43d4-9db8-03f76ec53ef5.mov

Resolves #557 
Resolves #629

### CODE REVIEW

File: packages/client/hmi-client/src/components/articles/Document.vue [hunk 1]
```diff
@@ -253,8 +253,13 @@ const formatCitation = (obj: { [key: string]: string }) => {
 	let citation: string;
 	if (Object.keys(obj).length <= 1) {
 		citation = obj.unstructured_citation ?? '';
+		citation = citation.replace(
+			/\bhttps?:\/\/\S+/,
+			`<a style='color: var(--text-color-subdued);' href=$&>$&</a>`
```
Comment (YohannParis) [inline packages/client/hmi-client/src/components/articles/Document.vue:258]: Really neat, I like when RegEx are nicely implemented.

It will be nicer to not add styling within the JS, and just add a class, or target the link within the AccordionTab directly.
```suggestion
			`<a href="$&">$&</a>`
```

**Review by YohannParis — APPROVED** [review]

File: packages/client/hmi-client/src/components/articles/Document.vue (hunk 1 above)
Comment (echl) [reply packages/client/hmi-client/src/components/articles/Document.vue:258]: I agree about styling, but that styling is already present in the css for this component and did not seem to get applied here (maybe because the html is dynamically generated?), so I had to add it inline.

Comment (YohannParis) [reply packages/client/hmi-client/src/components/articles/Document.vue:258]: You might have to add a `>>> a`  selector somewhere.

**Review by YohannParis — APPROVED** [review]
Great job!
