### PR TITLE
chore: fix code to model

### LINKED ISSUE #1771: [TASK] code to model
**Describe the task**
- [x] Finish the code to model integration within the `knowledge-middleware`.
- [x] Make sure that the process is working at least on the test.
- [ ] Implement it back onto the HMI by cleaning up and fixing `tera-code-editor`.

### PR DESCRIPTION
**Pull request by echl**
# Description

* Implement new `tera-code` component that implements code-to-model feature
* Kept the `code-editor` component for displaying .pdf files, for now
* Saving model currently not working due to recent model changes

https://github.com/DARPA-ASKEM/Terarium/assets/16358728/46c4c2a4-b569-44c2-8090-d747b56ab1fc

Resolves #1771

### CODE REVIEW

File: packages/client/hmi-client/src/services/knowledge.ts [hunk 1]
```diff
@@ -179,4 +179,23 @@ export const extractPDF = async (artifact: Artifact) => {
...
+		}
+		if (status === 'finished') {
+			return response.data.result?.job_result.amr;
+		}
+	}
+	logger.error(`Code to AMR request failed`, { toastTitle: 'Error - ta1-service' });
+	return null;
+}
+
 export { mathmlToAMR, latexToAMR };
```
Comment (YohannParis) [inline packages/client/hmi-client/src/services/knowledge.ts:201]: You should either add your function to this export, or remove this line.

File: packages/client/hmi-client/src/services/knowledge.ts [hunk 2]
```diff
@@ -179,4 +179,23 @@ export const extractPDF = async (artifact: Artifact) => {
...
+			if (extraction?.state === PollerState.Done) {
+				const data = extraction.data as any; // fix linting
+				return data?.job_result.amr;
+			}
+		}
+		if (status === 'finished') {
+			return response.data.result?.job_result.amr;
+		}
+	}
+	logger.error(`Code to AMR request failed`, { toastTitle: 'Error - ta1-service' });
```
Comment (YohannParis) [inline packages/client/hmi-client/src/services/knowledge.ts:197]:
```suggestion
	logger.error(`Code to AMR request failed`, { toastTitle: 'Error - knowledge-middleware' });
```

File: packages/client/hmi-client/src/services/knowledge.ts [hunk 3]
```diff
@@ -179,4 +179,23 @@ export const extractPDF = async (artifact: Artifact) => {
 	}
 };
 
+export async function codeToAMR(codeId: string) {
+	const response = await API.post(`/extract/code-to-amr?code_id=${codeId}`);
```
Comment (YohannParis) [inline packages/client/hmi-client/src/services/knowledge.ts:183]: if `name` and `description` are optional, why not remove them from our backend?
Should we let the user set them up when clicking on the call?
```suggestion
	const response = await API.post(`/knowledge/code-to-amr?code_id=${codeId}`);
```

File: packages/client/hmi-client/src/services/code.ts [hunk 4]
```diff
@@ -4,6 +4,39 @@ import { Ref } from 'vue';
...
+		return null;
+	}
+
+	return response.data as Code;
+}
+
+async function updateCodeAsset(
+	code: Code,
+	file: File,
+	progress: Ref<number>
```
Comment (YohannParis) [inline packages/client/hmi-client/src/services/code.ts:21]: What is this `progress`?

File: packages/client/hmi-client/src/page/project/components/tera-project-page.vue [hunk 5]
```diff
@@ -5,14 +5,12 @@
...
+	<tera-code
+		:project-id="project.id"
+		:asset-id="assetId ?? ''"
 		v-else-if="pageType === AssetType.Code"
-		:initial-code="code"
-		@vue:mounted="
-			emit('asset-loaded');
-			openCode();
-		"
+		@vue:mounted="() => emit('asset-loaded')"
```
Comment (YohannParis) [inline packages/client/hmi-client/src/page/project/components/tera-project-page.vue:12]: Why is this necessary?

File: packages/client/hmi-client/src/components/code/tera-code.vue [hunk 6]
```diff
@@ -0,0 +1,264 @@
...
+				modelName.value = extractedAmr.header.name;
+				isModalVisible.value = true;
+			}
+		}
+	}
+}
+
+async function saveModel() {
+	const modelToSave = model.value;
+	const createdModel = await createModel(modelToSave);
```
Comment (YohannParis) [inline packages/client/hmi-client/src/components/code/tera-code.vue:166]:
```suggestion
	const createdModel = await createModel(model.value);
```

File: packages/client/hmi-client/src/components/code/tera-code.vue [hunk 7]
```diff
@@ -0,0 +1,264 @@
+<template>
+	<main>
+		<header>
+			<section class="header">
+				<!-- <h4>{{ name }}</h4> -->
+				<section class="name">
+					<InputText v-model="codeName" class="name-input" />
+				</section>
```
Comment (YohannParis) [inline packages/client/hmi-client/src/components/code/tera-code.vue:8]: This should be a conditional if the asset as a name.

File: packages/client/hmi-client/src/components/code/tera-code.vue [hunk 8]
```diff
@@ -0,0 +1,264 @@
...
+			<tera-modal
+				v-if="isModalVisible && model"
+				class="modal"
+				@modal-mask-clicked="isModalVisible = false"
+				@modal-enter-press="isModalVisible = false"
+			>
+				<template #header>
+					<InputText v-model="modelName" class="name-input" />
+				</template>
+				<template #default>
```
Comment (YohannParis) [inline packages/client/hmi-client/src/components/code/tera-code.vue:42]: This is where you can add a `name` and `description` field. or even better re-use the create a new model modal.

File: packages/client/hmi-client/src/components/code/tera-code.vue (hunk 6 above)
Comment (YohannParis) [inline packages/client/hmi-client/src/components/code/tera-code.vue:165]: See comment in the resource endpoint about not needing to create a model

File: packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/knowledgemiddleware/KnowledgeResource.java [hunk 9]
```diff
@@ -106,16 +106,11 @@ public Model postLaTeXToAMR(
...
+		@QueryParam("name") String name,
+		@QueryParam("description") String description
 	) {
-		// Fetch the related artifact to fill potential missing name and description
-		final Artifact artifact = artifactProxy.getArtifact(artifactId);
-		if (name == null) {	name = artifact.getName(); }
-		if (description == null) { description = artifact.getDescription();	}
-
-		return knowledgeMiddlewareProxy.postCodeToAMR(artifactId, name, description);
+		return knowledgeMiddlewareProxy.postCodeToAMR(codeId, name, description);
```
Comment (YohannParis) [inline packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/knowledgemiddleware/KnowledgeResource.java:113]: [It returns more](https://github.com/DARPA-ASKEM/knowledge-middleware/blob/main/worker/operations.py#L509-L515) than just a `Model`.
This would be useful to maybe display the model directly by open it instead of returning the AMR?

File: packages/client/hmi-client/src/components/code/tera-code.vue (hunk 7 above)
Comment (echl) [reply packages/client/hmi-client/src/components/code/tera-code.vue]: I wanted to test something out here; I think the title (if editable) should always be an InputText. What's the point of having a separate edit button and having extra conditional logic? What do you think @jamiewaese-uncharted 

https://github.com/DARPA-ASKEM/Terarium/assets/16358728/2af113c7-76db-4a57-95dd-e95ea8563c9c

File: packages/client/hmi-client/src/components/code/tera-code.vue (hunk 6 above)
Comment (echl) [reply packages/client/hmi-client/src/components/code/tera-code.vue:165]: Good catch, leftover from when I had to wrangle the value of modelToSave since it had `header` in it

File: packages/client/hmi-client/src/components/code/tera-code.vue (hunk 7 above)
Comment (YohannParis) [reply packages/client/hmi-client/src/components/code/tera-code.vue]: I don't think we should do that. If a user click on it by inadvertence and type keys that get saved automatically. This will be really error prone.

File: packages/client/hmi-client/src/components/code/tera-code.vue
Comment (YohannParis) [inline packages/client/hmi-client/src/components/code/tera-code.vue:1]: This component should use `tera-asset`, and it is missing here.

File: packages/client/hmi-client/src/services/code.ts (hunk 4 above)
Comment (echl) [reply packages/client/hmi-client/src/services/code.ts:21]: It's required in `addFileToCodeAsset` which is being called in this method

Comment (YohannParis) [reply packages/client/hmi-client/src/services/code.ts:21]: Then why are we not displaying it in the button?
If this would take too long, could you write an issue to add this feature please?

File: packages/client/hmi-client/src/components/code/tera-code.vue (hunk 7 above)
Comment (echl) [reply packages/client/hmi-client/src/components/code/tera-code.vue]: It seems very unlikely to me that a user would actually accidentally click it. If they do, anything they accidentally type is very noticeable, and the consequences are trivial and easy to undo (the name does not automatically save when you focus out of the element). 

Whereas having to click a small edit button is much more annoying, and the user will face this annoyance almost every time.

File: packages/client/hmi-client/src/components/code/tera-code.vue [hunk 10]
```diff
@@ -0,0 +1,264 @@
...
+		if (newCodeAsset && newCodeAsset.id) {
+			const extractedAmr = await codeToAMR(newCodeAsset.id);
+			if (extractedAmr) {
+				model.value = extractedAmr as Model;
+				modelName.value = extractedAmr.header.name;
+				isModalVisible.value = true;
+			}
+		}
+	}
+}
```
[the remark this answers is not in the document]
Comment (echl) [reply packages/client/hmi-client/src/components/code/tera-code.vue]: Already fixed, I just got rid of the condition. It should save every time you click extract in case content has changed (and to save user a click)

File: packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/knowledgemiddleware/KnowledgeResource.java (hunk 9 above)
Comment (echl) [reply packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/knowledgemiddleware/KnowledgeResource.java:113]: Not sure what you mean. The model already gets saved in tds as a result of calling code-to-amr?

File: packages/client/hmi-client/src/components/code/tera-code.vue
Comment (echl) [reply packages/client/hmi-client/src/components/code/tera-code.vue:1]: What does `tera-asset` have in it that `tera-code` needs? I don't think `tera-code` is using any of the functionality inside `tera-asset`

Comment (YohannParis) [reply packages/client/hmi-client/src/components/code/tera-code.vue:1]: `tera-asset` is the component that all asset uses to derive the same basic behaviour, so yes it needs it.

File: packages/client/hmi-client/src/services/knowledge.ts [hunk 11]
```diff
@@ -179,4 +185,21 @@ export const extractPDF = async (artifact: Artifact) => {
...
+			if (extraction?.state === PollerState.Done) {
+				const data = extraction.data as any; // fix linting
+				return data?.job_result.amr;
+			}
+		}
+		if (status === 'finished') {
+			return response.data.result?.job_result.amr;
+		}
+	}
+	logger.error(`Code to AMR request failed`, { toastTitle: 'Error - knowledge-middlewareõ' });
```
Comment (YohannParis) [inline packages/client/hmi-client/src/services/knowledge.ts:203]:
```suggestion
	logger.error(`Code to AMR request failed`, { toastTitle: 'Error - knowledge-middleware' });
```

File: packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/knowledgemiddleware/KnowledgeResource.java (hunk 9 above)
Comment (YohannParis) [reply packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/knowledgemiddleware/KnowledgeResource.java:113]: Right now we use the response to display the AMR, but we still don't open it, there is a `createModel` call made after this.

File: packages/client/hmi-client/src/components/code/tera-code.vue (hunk 7 above)
Comment (ngraham76) [reply packages/client/hmi-client/src/components/code/tera-code.vue]: Is the title of an asset changed often? If not, I would think we should stick with the current design of clicking an edit button to enable the input field to avoid inadvertently re-naming the assets as Yohann mentioned. Thoughts @jamiewaese-uncharted and @pascaleproulx ?

Comment (jamiewaese-uncharted) [reply packages/client/hmi-client/src/components/code/tera-code.vue]: Maybe we can use the PrimeVue `inplace` component here: https://primevue.org/inplace/#basic

It would look sorta like this, but we use a heading font size, and we add an 'X' button to cancel and a checkmark button to confirm.

vue inplace

File: packages/client/hmi-client/src/components/code/tera-code.vue
Comment (echl) [reply packages/client/hmi-client/src/components/code/tera-code.vue:1]: Could we possibly address this in another pr? Looking at `tera-asset` I honestly don't think there is any important functionality that is missing without it in this particular case.

File: packages/client/hmi-client/src/components/code/tera-code.vue (hunk 7 above)
Comment (YohannParis) [reply packages/client/hmi-client/src/components/code/tera-code.vue]: Sure @echl if you could make a ticket of it.

File: packages/client/hmi-client/src/components/code/tera-code.vue
Comment (YohannParis) [reply packages/client/hmi-client/src/components/code/tera-code.vue:1]: ... Okay write the issue, but we need to do it, even if for now it's not needing any functionality.
When we move to multiple tabs, SSE, windows, we will be working against `tera-asset` and not each sub-component.

**Review by YohannParis — APPROVED** [review]
