### PR TITLE
[BUG]: download model-configurations is broken #6407

### LINKED ISSUE #6407: [BUG]: download model-configurations is broken
**Describe the bug**
downloading a model configuration should be updated to be named `Download as configure model` and call the following endpoint `model-configurations/as-configured-model/`

### PR DESCRIPTION
**Pull request by dvince2**
# Description

* Adding a new option to download a configured model in addition to the zipped archive

Resolves #6407

### CODE REVIEW

File: packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-configuration-item.vue [hunk 1]
```diff
@@ -27,7 +27,7 @@ import { ref } from 'vue';
 import { useConfirm } from 'primevue/useconfirm';
 import { deleteModelConfiguration } from '@/services/model-configurations';
 
-const emit = defineEmits(['delete', 'use', 'download']);
+const emit = defineEmits(['delete', 'use', 'downloadArchive', 'downloadModel']);
```
Comment (YohannParis) [inline packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-configuration-item.vue:30]: Why not doing the download here, you already have the configuration?
I do not see the need for extra emit here.

Comment (dvince2) [reply packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-configuration-item.vue:30]: Mostly just to match the style of whats going on in here - there are 3 buttons that all use `emit`, it would have felt weird to add a fourth and make it work differently.

File: packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue [hunk 2]
```diff
@@ -577,6 +579,21 @@ const downloadModelArchive = async (configuration: ModelConfiguration = knobs.va
...
+const downloadModel = async (configuration: ModelConfiguration = knobs.value.transientModelConfig) => {
+	if (!configuration.id) return;
+
+	const configuredModel = await getAsConfiguredModel(configuration.id);
+	if (configuredModel) {
+		const data = `text/json;charset=utf-8,${encodeURIComponent(JSON.stringify(configuredModel, null, 2))}`;
+		const a = document.createElement('a');
+		a.href = `data:${data}`;
+		a.download = `${configuredModel.name ?? 'model'}.json`;
+		a.innerHTML = 'download JSON';
```
[the remark this answers is not in the document]
Comment (dvince2) [reply packages/client/hmi-client/src/components/workflow/ops/model-config/tera-model-config-drilldown.vue:591]: thanks!

**Review by mwdchang — APPROVED** [review]
