### PR TITLE
fix[hmi-server]: Dataset extract columns, doing it on GET if not present

### LINKED ISSUE #2784: Dataset extract columns, doing it on GET if not present

### PR DESCRIPTION
**Pull request by dvince2**
# Description

This is actually the fix for incorrect column information after a beaker-driven transform too. There is a corresponding change on beaker that blows away column data (https://github.com/DARPA-ASKEM/beaker-kernel/pull/95) since columns and/or data will have changed in modified datasets. Then on a GET call we repopulate the column data because its empty.  This will also cover any situation where a CSV/dataset was some how uploaded and the column data was empty too. In addition, this centralizes some code around getting CSV files and updating headers.

Resolves #2784

### CODE REVIEW

File: packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DatasetController.java [hunk 1]
```diff
@@ -202,6 +187,45 @@ public ResponseEntity<Dataset> getDataset(@PathVariable("id") final UUID id) {
...
+		}
+
+		if(dataset.get().getColumns() != null && !dataset.get().getColumns().isEmpty()){
+			//columns are set. No need to extract
+			return dataset;
+		}
+		if(dataset.get().getFileNames() == null || dataset.get().getFileNames().isEmpty()){
+			//no file names to extract columns from
+			return dataset;
+		}
```
Comment (YohannParis) [inline packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DatasetController.java:209]: Let's change that to make sure that we update the missing columns fields.
Because the CSV might be updated and therefore need to re-run this for the new or remove columns.

**Review by YohannParis — APPROVED** [review]

File: packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DatasetController.java (hunk 1 above)
Comment (dvince2) [reply packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DatasetController.java:209]: These are quick failure cases - in this case here there are no files attached to the dataset (so no CSV to read headers from)

In the case above it we only continue when the column fields are empty (beaker blows away the column metadata when it does a transform now). We don't want to do this column check on every get because it is EXPENSIVE - we need to fetch the CSV file to do it
