### PR TITLE
fix issue where LLM makes up information when enriching datasets

### LINKED ISSUE #6076: [BUG]: LLM makes up information when enriching dataset
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

Image

**Additional context**

### PR DESCRIPTION
**Pull request by dgauldie**
# Description

* Include a summary of the changes and the related issue. 
* Include relevant motivation and context.

Resolves #6076 , #6078

### CODE REVIEW

File: packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/EnrichDatasetResponseHandler.java [hunk 1]
```diff
@@ -125,10 +135,6 @@ public TaskResponse onSuccess(final TaskResponse resp) {
 				metadata.put("description", description);
 				metadata.put("unit", unit);
 
-				// Based on the name, description, fetch the best grounding available and add it to the metadata
-				// final DKG grounding = dkgService.knnSearchEpiDKG(0, 1, 1, name + " " + description, null)
-				// metadata.put("grounding", grounding);
-
```
Comment (YohannParis) [inline packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/EnrichDatasetResponseHandler.java:131]: Why removing this comment.

**Review by YohannParis — APPROVED** [review]

File: packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/EnrichDatasetResponseHandler.java (hunk 1 above)
Comment (dgauldie) [reply packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/tasks/EnrichDatasetResponseHandler.java:131]: because its a comment... and it's broken anyway.
