### PR TITLE
fix: blank project page

### LINKED ISSUE #579: [BUG]: Removing papers from project takes me to a grey screen (sometimes)
**Describe the bug**
Sometimes when I remove papers from my project, it takes me to a gray screen instead of keeping me in the same spot and updating the list. 

**To Reproduce**
Go to the project space, in the project space go to papers, remove a paper from the list (you may see that portion of the screen go grey.)

**Expected behavior**
Should keep me in my list of papers and remove the paper.

**Screenshots**
image

**Additional context**

### PR DESCRIPTION
**Pull request by echl**
Fix missing null check in `resources-list` preventing project page from rendering and breaking the app.
Fix `resources-list` not loading the proper resources the first time you visit the project page from a different page. 

https://user-images.githubusercontent.com/16358728/217023136-905c94c1-cc75-44e9-af5e-f9c756495983.mov

Resolves #579

### CODE REVIEW

File: packages/client/hmi-client/src/components/resources/resources-list.vue [hunk 1]
```diff
@@ -30,25 +30,34 @@ const filteredRouteMetadata: {
...
-	}
+}
+
+resources.value = updateResources();
+
+// @ts-ignore
+// eslint-disable-next-line @typescript-eslint/no-unused-vars
+resourcesStore.$subscribe((mutation, state) => {
+	resources.value = updateResources();
 });
```
Comment (YohannParis) [inline packages/client/hmi-client/src/components/resources/resources-list.vue:61]: Can you just replace `(mutation, state)` with `()` to remove all those ts and esling ignore line?
If not, then we need to look into a better solution or remove those rules.

**Review by YohannParis — APPROVED** [review]
Great, thank you!

File: packages/client/hmi-client/src/components/resources/resources-list.vue (hunk 1 above)
Comment (echl) [reply packages/client/hmi-client/src/components/resources/resources-list.vue]: Done!

**Review by YohannParis — APPROVED** [review]
