### PR TITLE
4149 constraint drop down should not have observables these are broken in pyciemss at the moment

### LINKED ISSUE #4149: constraint drop down should not have observables - these are broken in pyciemss at the moment

### PR DESCRIPTION
**Pull request by YohannParis**
# Description

* Rename ContraintGroup to appropriate `Criterion`
* Remove the observables from the dropdown
* Clean up few things

Resolves #4149

### CODE REVIEW

**Review by Tom-Szendrey — APPROVED** [review]
ty

File: packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/optimize-ciemss-operation.ts [hunk 1]
```diff
@@ -57,7 +57,7 @@ export interface OptimizeCiemssOperationState extends BaseState {
 	interventionPolicyId: string; // Used to determine if we need to reset the InterventionPolicyGroupForm.
 	interventionPolicyGroups: InterventionPolicyGroupForm[];
 	// Constraints:
-	constraintGroups: ConstraintGroup[];
+	constraintGroups: Criterion[];
```
Comment (mwdchang) [inline packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/optimize-ciemss-operation.ts:60]: Are we going all the way and rename the field as well? e.g. it still says "state.constraintGroups"

Comment (YohannParis) [reply packages/client/hmi-client/src/components/workflow/ops/optimize-ciemss/optimize-ciemss-operation.ts:60]: It would be great to do so. But the PR is quite big already, and I thought stopping here will be good for now.
I want to keep doing the cleaning, maybe in another PR soo.

**Review by blanchco — APPROVED** [review]
