### PR TITLE
[fix: hmi-server] Add safety code to sciml message reading

### LINKED ISSUE #2239: Add safety code to sciml message reading. Begin back end work for individual queues

### PR DESCRIPTION
**Pull request by dvince2**
This is some back end legwork.
* Adding safety to message parsing
* Better error message for problems parsing
* Sciml and pyciemss now use individual queues
* Some safety code in case someone's hostname is staging or production. This isn't an exhaustive safety plan but enough to stop an accident ;)
* Note that this will break sciml messages from coming in in the current form as the sciml service is hard coded against a specific queue name. However since thats all broken anyway, its not a big loss ;)
@Jami159 you'll need to hard code your queue name locally though until part two of this is in

Resolves #2239

### CODE REVIEW

File: packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/SimulationEventService.java [hunk 1]
```diff
@@ -95,21 +106,23 @@ private void onScimlSendToUserEvent(final Message message, final Channel channel
...
      */
     @RabbitListener(
-            queues = {PYCIEMSS_QUEUE},
+            queues = "${terarium.simulation-status}${terarium.queue.suffix:${terarium.userqueue.suffix}}",
             concurrency = "1")
     private void onPyciemssSendToUserEvent(final Message message, final Channel channel) throws IOException {
-        // TODO this should mirror the implementation of onScimlSendToUserEvent
+
+			/*
+				//TODO implement PyciemssStatusUpdate
```
Comment (Tom-Szendrey) [inline packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/SimulationEventService.java:114]: Is there an issue we can link to this todo?

Comment (dvince2) [reply packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/SimulationEventService.java:114]: There is no issue... logging one would be good but I don't know who or what it would be or what the status/holdup is. @mwdchang ?

Comment (mwdchang) [reply packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/SimulationEventService.java:114]: I will create an issue if none exist - the hold up is ciemss is doing a big refactor over their codebase and we are not expecting to have a usable intermediate result in the next short little while.

Comment (dvince2) [reply packages/server/src/main/java/software/uncharted/terarium/hmiserver/service/SimulationEventService.java:114]: In theory once they're done their refactor then the only backend work will be to implement the `PyciemssStatusUpdate` model. Everything else should automagically work.

**Review by mwdchang — APPROVED** [review]
