### PR TITLE
Fix calibrate chart errors

### LINKED ISSUE #5231: [BUG]: observations circles on the calibrate charts do not show
**Describe the bug**
observations circles on the calibrate charts which do not show anymore (both on staging and prod)

### PR DESCRIPTION
**Pull request by jryu01**
# Description

- Fixed the issue that ground truth data wasn't showing (#5231)
- Fixed the issue that the error chart wasn't showing (#5281)

Screenshot 2024-10-25 at 3 34 30 PM

Resolves #5231, #5281

### CODE REVIEW

File: packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue [hunk 1]
```diff
@@ -749,6 +750,9 @@ const generateAnnotation = async (setting: ChartSetting, query: string) => {
 };
 // ---
 
+const errorData = computed<Record<string, any>[]>(() =>
```
Comment (Tom-Szendrey) [inline packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue:753]: Why do we need to move this into a computed? I am not understanding the issue

**Review by Tom-Szendrey — APPROVED** [review]

**Review by blanchco — APPROVED** [review]

File: packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue (hunk 1 above)
Comment (jryu01) [reply packages/client/hmi-client/src/components/workflow/ops/calibrate-ciemss/tera-calibrate-ciemss-drilldown.vue:753]: `groundTruthData` which `errorData` is dependant on is a reactive variable. Which get's now computed and populated asynchronously by
```
			setupCsvAsset(dataset).then((csv) => {
				csvAsset.value = csv;
			});
```
Thus the ground truth data isn't available until csvAssts get's assigned and we need to reflect the change accordingly when that value is updated.
