### PR TITLE
[BUG]: 400 error occurs when navigating from workflow to home

### LINKED ISSUE #3672: [BUG]: 400 error occurs when navigating from `/projects/{pid}/ workflow/{wid}` to main root page (`/`)
**Describe the bug**
400 error occurs when navigating from `/projects/{pid}/ workflow/{wid}` to main root page (`/`)

**To Reproduce**
1. Create a project -> Upload a model
2. Create a workflow -> Add the created model
3. Click `terarium` logo to navigate to the main page. 
4. See 400 error

When navigating from the workflow page, it seems, GET `workflow/{wid}` is being called and getting error missing projectId from the main page.

### PR DESCRIPTION
**Pull request by dvince2**
# Description

Saving the active project id in the workflow, as when we unmount this component we lose this injection later on.

Resolves #3672

### CODE REVIEW

File: packages/client/hmi-client/src/components/workflow/tera-workflow.vue [hunk 1]
```diff
@@ -308,7 +310,7 @@ async function updateWorkflowName() {
 
 // eslint-disable-next-line
 const _saveWorkflow = async () => {
-	await workflowService.updateWorkflow(wf.value.dump());
+	await workflowService.updateWorkflow(wf.value.dump(), currentProjectId.value ?? undefined);
```
Comment (mwdchang) [inline packages/client/hmi-client/src/components/workflow/tera-workflow.vue:313]: Can we just use `activeProjectId` directly instead of through an additional var "currentProjectId"?

Comment (dvince2) [reply packages/client/hmi-client/src/components/workflow/tera-workflow.vue:313]: no, because once we hit the `onUnmounted` the active project has been cleared away (This is why the injection in `api.ts` is failing)

**Review by mwdchang — APPROVED** [review]

**Review by YohannParis — APPROVED** [review]

**Review by Tom-Szendrey — APPROVED** [review]
LGTM
