### PR TITLE
fix issue with concepts not showing up properly

### LINKED ISSUE #2926: [BUG]: dataset concepts are not showing up properly
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by dgauldie**
# Description

* Include a summary of the changes and the related issue. 
* Include relevant motivation and context.

Resolves #2926

### CODE REVIEW

File: packages/client/hmi-client/src/components/dataset/tera-dataset-description.vue [hunk 1]
```diff
@@ -25,7 +25,7 @@
 				@enriched="fetchAsset"
 			/>
 		</AccordionTab>
-		<AccordionTab header="Column information">
+		<AccordionTab header="Column Information">
```
Comment (YohannParis) [inline packages/client/hmi-client/src/components/dataset/tera-dataset-description.vue:28]: No capital case in the app. This should go back to lowercase.

**Review by YohannParis — APPROVED** [review]
