### PR TITLE
Layout of model entry form is broken when latex expressions are too long

### LINKED ISSUE #4574: [BUG]: Column widths/alignments of the `Observables` table are broken in the `Model` operator when the math expression is too long
**Describe the bug**
The widths of the `Observables` table in the `Model` operator is broken when the sympy math expression is really long, causing a horizontal scrollbar to appear.

**To Reproduce**
1. Go to https://app.staging.terarium.ai/projects/80bfb79e-808c-45bc-a96e-7addeef46557/workflow/641e25b2-e62d-4f20-8fb9-ac32d88db8e0?operator=81a97aa9-a6e0-4e03-9735-4f53aa56cb0c

**Expected behavior**
The `R0 | R0 | Unit [Add a unit] ...` stuff should not slide around and should stay aligned with the other rows.

**Screenshots**
Screenshot 2024-08-23 at 4 45 28 PM
 help explain your problem.

### PR DESCRIPTION
**Pull request by brittanykondo**
* removed grid and used flex in model entry form

Screenshot 2024-10-16 at 8 06 32 PM

Resolves #4574

### CODE REVIEW

File: packages/client/hmi-client/src/components/model/model-parts/tera-model-part-entry.vue [hunk 1]
```diff
@@ -135,63 +138,25 @@ if (props.item.description) showDescription.value = true;
 
 <style scoped>
 section {
-	display: grid;
-	grid-template-areas:
-		'symbol name unit . concept'
-		'expression expression expression expression expression'
-		'description description description description description';
-	grid-template-columns: max-content max-content max-content auto max-content;
```
Comment (YohannParis) [inline packages/client/hmi-client/src/components/model/model-parts/tera-model-part-entry.vue:143]: Why not just adding a `grid-template-rows` to make the expression as tall as needed?

**Review by YohannParis — APPROVED** [review]

**Review by shawnyama — APPROVED** [review]
Awesome!

`tera-column-info` (used in `tera-dataset`) has the same grid styles, idk if it's worth changing too. I haven't heard of any overflow problems there.
