### PR TITLE
[BUG]: Incorrect column info in the Dataset page of an uploaded CSV file with `,` in column headers #4994

### LINKED ISSUE #4994: [BUG]: Incorrect column info in the Dataset page of an uploaded CSV file with `,` in column headers
**Describe the bug**

Question 1 of Problem 4 of the monthly demo scenarios asks the user to extract some datasets to Terarium. They can be simply downloaded from the paper website and uploaded to Terarium.

However, the Dataset page of the flow rates CSV file has two minor bugs:
1. The data table is parsed correctly (4 columns) but the "Column information" section shows 6 columns; the issue is probably the `,` in the column headers.
2. "Enrich metadata with AI" failed to provide summary info for 4 of the 6 columns in the info section, probably due to the above issue.

Screenshot 2024-09-30 at 5 47 55 PM

**To Reproduce**
1. Upload this CSV file [flow rates in the wastewater treatment plant_Total_flow.csv](https://github.com/user-attachments/files/17196743/flow.rates.in.the.wastewater.treatment.plant_Total_flow.csv)
3. Go to its Dataset page
4. Note the number of columns in the info section vs. the data table
5. Note the lack of summary info for 4 of the columns in the info section.

### PR DESCRIPTION
**Pull request by dvince2**
# Description

* Changing our CSV parsing to use apache commons
* Updating pinned version of `commons-csv`, `commons-text` and adding new dependency to `commons-io` for CSV ingest.
* Moving statistics generation to `DatasetService`
* General dataset code cleanup

Resolves #4994

### CODE REVIEW

**Review by YohannParis — APPROVED** [review]

File: packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DatasetController.java [hunk 1]
```diff
@@ -450,9 +461,20 @@ public ResponseEntity<ResponseStatus> uploadCsvFromGithub(
...
+		CSVParser csvParser = null;
+		try {
+			csvParser = new CSVParser(
+				new StringReader(csvString),
+				CSVFormat.Builder.create(CSVFormat.DEFAULT).setHeader().setSkipHeaderRecord(false).build()
+			);
+		} catch (IOException e) {
+			final String error = "Unable to parse csv from github";
+			log.error(error);
+			throw new ResponseStatusException(org.springframework.http.HttpStatus.INTERNAL_SERVER_ERROR, error);
```
Comment (dgauldie) [inline packages/server/src/main/java/software/uncharted/terarium/hmiserver/controller/dataservice/DatasetController.java:473]: this should be from messages.properties

**Review by kbirk — APPROVED** [review]
