### PR TITLE
fix: make loading gif primary green; fix links in explorer article preview panel

### LINKED ISSUE #638: [BUG]: Fix links in Explorer Article Preview panel
The links in the Explorer Article Preview panel need some tweaks:
1) The DOI link should open in a new tab so we don't lose our place in Terarium
2) The Open PDF button should not be shown if it doesn't actually link to a PDF. It shouldn't link to the publisher page. That's what the DOI link is for.

preview window links

### LINKED ISSUE #639: [BUG]: Make loading gif primary green
Our loading gif is the wrong green. It should be primary green: #1B8073
loading_gif

### PR DESCRIPTION
**Pull request by echl**
https://user-images.githubusercontent.com/16358728/217056755-b9c9447a-1467-4efe-b3e5-562a23dd4107.mov

Resolves #638
Resolves #639

### CODE REVIEW

File: packages/client/hmi-client/src/components/articles/Document.vue [hunk 1]
```diff
@@ -11,12 +11,13 @@
 						<a
 							:href="`https://doi.org/${doi}`"
 							rel="noreferrer noopener"
+							target="_blank"
```
Comment (YohannParis) [inline packages/client/hmi-client/src/components/articles/Document.vue:14]: Let's remove this, unless it was specified by Jamie, Holly or Pascale.

File: packages/client/hmi-client/src/components/data-explorer/search-results-list.vue [hunk 2]
```diff
@@ -170,7 +170,9 @@ const resultsText = computed(() => {
 });
 </script>
 
-<style scoped>
+<style scoped lang="scss">
+@import '@/assets/css/theme/variables';
+
```
Comment (YohannParis) [inline packages/client/hmi-client/src/components/data-explorer/search-results-list.vue:175]: We use the CSS custom properties to avoid doing this.
Please use them instead 😃

**Review by YohannParis — APPROVED** [review]

File: packages/client/hmi-client/src/components/articles/Document.vue [hunk 3]
```diff
@@ -251,6 +252,11 @@ const relatedTerariumDocuments = computed(
 	() => relatedTerariumArtifacts.value.filter((d) => isXDDArticle(d)) as XDDArticle[]
 );
 
+function hasPdf() {
```
Comment (mwdchang) [inline packages/client/hmi-client/src/components/articles/Document.vue:255]: Nitpick: hasPdf => hasPDF to keep language more consistent.

File: packages/client/hmi-client/src/components/articles/Document.vue (hunk 1 above)
Comment (echl) [reply packages/client/hmi-client/src/components/articles/Document.vue:14]: This one is part of the requirement :)

File: packages/client/hmi-client/src/components/data-explorer/search-results-list.vue (hunk 2 above)
Comment (echl) [reply packages/client/hmi-client/src/components/data-explorer/search-results-list.vue:175]: Sorry, not sure I understand. We want to use standard css variables like `var(--something)`? Then I would have to define that in `/styles/variables.css`? Any way I can leverage the existing variable?

Comment (echl) [reply packages/client/hmi-client/src/components/data-explorer/search-results-list.vue:175]: Nevermind I see how it is done with existing variables!

**Review by YohannParis — APPROVED** [review]
